import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavMenu from "./NavMenu";
import AuthProvider from "./AuthProvider";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={poppins.className}>
          <NavMenu />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
